#!/usr/bin/env python3
"""Build metrics, the readable report, narrative facts and the demo payload from saved
decisions (no model calls). This is the ONLY writer of work/results/metrics.json,
work/results/facts.json, work/results/demo_data.json and the readable report,
outputs/7_results-report.md (paths in zeroops/paths.py).

  ./jev/bin/python scripts/report.py [--allow-stale]

Decision files whose corpus_version differs from the current corpus are skipped (with a
warning) unless --allow-stale is given: scoring old answers against new labels is how the
first version of this report compared backends unfairly.
"""
from __future__ import annotations

import argparse
import glob
import json
import statistics
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from rich.console import Console  # noqa: E402
from rich.table import Table  # noqa: E402

from zeroops.corpus import corpus_fingerprint, generate_corpus  # noqa: E402
from zeroops.facts import LABELS, LOCAL, ORDER, build_facts  # noqa: E402
from zeroops.metrics import compute_metrics  # noqa: E402
from zeroops.paths import DECISIONS_GLOB, DEMO_DATA, FACTS, LAB_DIR, METRICS, REPORT, RESULTS, rel  # noqa: E402

console = Console(width=170)
CORPUS = generate_corpus(n_variants=4)
VERSION = corpus_fingerprint(CORPUS)


def load_records(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def fmt(v, spec: str = ".0f", none: str = "–") -> str:
    """Format a possibly-missing number."""
    return none if v is None else format(v, spec)


def frac(k: int, n: int) -> str:
    return f"{k}/{n} ({round(100 * k / n)}%)" if n else "–"


def build_report_md(per_backend: dict[str, list[dict]], metrics: dict[str, dict], facts: dict) -> str:
    names = [n for n in ORDER if n in per_backend]
    n = facts["n"]
    L: list[str] = []
    L.append(f"# Results: four models, same questions, {n} synthetic incidents\n")
    L.append("*Our measurement.* Generated by `scripts/report.py` from `work/results/decisions_*.jsonl`; "
             f"do not edit by hand. Corpus version `{facts['corpus_version']}`.\n")
    L.append(f"Each backend received the same 12 typed questions for each of {n} incidents, and the same "
             "gate (`zeroops/policy.py`) turned its answers into AUTO (act without a person), ESCALATE "
             "(page a person) or OBSERVE (log only).\n")
    L.append(f"**Read these numbers as a smoke test.** The incidents are synthetic: {facts['n_templates']} "
             "hand-written templates, each used 4 times with different service names and numbers, so the "
             f"evidence is closer to {facts['n_templates']} cases than to {n}. The clues are explicit, which is "
             "why root cause is near 100%. There is no held-out set: the thresholds were set by hand and "
             "have never been tried on other incidents. Answer options were always listed in the same "
             f"order. One incident is worth {100 / n:.1f} percentage points.\n")
    models = ", ".join(f"{LABELS[k]} = `{facts['backends'][k]['model']}`" for k in names)
    L.append(f"Model versions recorded in the decision logs: {models}.\n")

    # --- table 1: answer quality -------------------------------------------------
    L.append("## 1. Were the answers right?\n")
    L.append("Counts are out of all incidents that returned answers.\n")
    L.append("| Backend | Category (7 options) | Root cause (11 options) | Action: exact match | "
             "Action: acceptable* | Severity within 1 level (4 levels) |")
    L.append("|---|---|---|---|---|---|")
    for k in names:
        b = facts["backends"][k]
        na = b["n_answered"]
        L.append(f"| {LABELS[k]} | {frac(b['category']['k'], na)} | {frac(b['root_cause']['k'], na)} | "
                 f"{frac(b['action_exact']['k'], na)} | {frac(b['action_acceptable']['k'], na)} | "
                 f"{frac(b['severity_within_1']['k'], na)} |")
    L.append("")
    L.append("Which first action each backend proposed, against our labels (counts out of all incidents; "
             "options were listed to the model in this order, rollback first):\n")
    acts = ["rollback", "patch_config", "restart", "scale_up", "failover", "drain", "escalate", "observe"]
    L.append("| | " + " | ".join(acts) + " |")
    L.append("|---|" + "---|" * len(acts))
    lab = per_backend[names[0]]
    L.append("| Our labels | " + " | ".join(str(sum(r["ground_truth"]["correct_action"] == a for r in lab))
                                          for a in acts) + " |")
    for k in names:
        recs = [r for r in per_backend[k] if not r.get("error")]
        L.append(f"| {LABELS[k]} | " + " | ".join(str(sum(r["pred"]["proposed_action"] == a for r in recs))
                                                for a in acts) + " |")
    L.append("")

    # --- table 2: what the gate did ------------------------------------------------
    L.append("## 2. What did the gate do with those answers?\n")
    L.append(f"{facts['n_unsafe']} of the {n} incidents are labelled *unsafe to automate* (dependency outage, "
             "network partition, database saturation, data corruption, security incident; 4 of each). "
             f"{facts['n_real']} are real incidents; the rest are monitoring flukes and planned maintenance.\n")
    L.append("| Backend | Acted alone (AUTO) | Of those: exact action | Of those: labelled unsafe | "
             "Unsafe scenario types automated | Unsafe cases paged to a person | "
             "Real incidents logged as noise | Paged | Logged |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for k in names:
        b = facts["backends"][k]
        a = metrics[k]["autonomy"]
        na = b["n_answered"]
        unsafe_paged = round((a["escalation_recall_pct"] or 0) * a["unsafe_cases"] / 100)
        upper = b["unsafe_templates_upper95_pct"]
        L.append(f"| {LABELS[k]} | {frac(b['auto'], na)} | "
                 f"{frac(b['auto_exact'], b['auto']) if b['auto'] else 'never acted'} | "
                 f"{frac(b['unsafe_auto'], b['auto']) if b['auto'] else 'never acted'} | "
                 f"{b['unsafe_templates_automated']} of {b['unsafe_templates']}"
                 f"{f' (95% upper bound {upper:.0f}%)' if upper is not None else ''} | "
                 f"{frac(unsafe_paged, a['unsafe_cases'])} | {b['missed_incidents']} | "
                 f"{b['escalate']} | {b['observe']} |")
    L.append("")
    j = facts.get("jev")
    if j and j["autos_near_page_cutoff"]["k"]:
        near = j["autos_near_page_cutoff"]
        sens = {s["thresholds"]["page_min"]: s["auto"] for s in j["sensitivity"]}
        L.append(f"How close the calls were ({LABELS['jev_native']}): in {near['k']} of the {near['of']} AUTO "
                 f"decisions the \"should a human be paged?\" probability was between {near['min']:.2f} and "
                 f"{near['max']:.2f}, just under the {near['cutoff']:.2f} cut-off. With the cut-off at 0.80 the "
                 f"gate would have automated {sens.get(0.8)} incidents, at 0.85 {sens.get(0.85)}. The Threshold "
                 f"Lab (`{rel(LAB_DIR)}/`) shows the full curve.\n")

    # --- table 3: speed and cost ---------------------------------------------------
    L.append("## 3. Speed and cost\n")
    L.append("| Backend | Median latency | 95th percentile | Cost per 1,000 incidents | Where the cost figure comes from |")
    L.append("|---|---|---|---|---|")
    for k in names:
        b = facts["backends"][k]
        cost = "$0" if k in LOCAL else (f"${b['cost_per_1k_usd']:.3f}" if b["cost_per_1k_usd"] is not None else "–")
        L.append(f"| {LABELS[k]} | {fmt(b['p50_ms'])} ms | {fmt(b['p95_ms'])} ms | {cost} | {b['cost_basis']} |")
    L.append("\nLatency is wall-clock per call from the author's workstation, run once; network distance "
             "to the hosted APIs is included. Local models ran on the author's GPU (RTX 5080 laptop).\n")

    # --- calibration ---------------------------------------------------------------
    L.append("## 4. Does confidence track accuracy? (failure category)\n")
    L.append("Answers grouped by the model's stated confidence. If confidence were reliable, accuracy "
             "would rise with each row and match it. Groups with fewer than ~10 answers can swing by "
             "20-50 points on a single incident.\n")
    L.append("| Confidence | " + " | ".join(LABELS[k] for k in names) + " |")
    L.append("|---|" + "---|" * len(names))
    buckets = sorted({b["bucket"] for k in names for b in metrics[k]["calibration"]})
    for bk in buckets:
        cells = []
        for k in names:
            b = next((x for x in metrics[k]["calibration"] if x["bucket"] == bk), None)
            cells.append(f"{b['correct']}/{b['n']} right" if b else "–")
        L.append(f"| {bk} | " + " | ".join(cells) + " |")
    L.append("| Expected calibration error | " + " | ".join(fmt(metrics[k]["calibration_ece"], ".2f")
                                                      for k in names) + " |")
    L.append("")

    # --- definitions ---------------------------------------------------------------
    L.append("## Column definitions\n")
    L.append("- **Action: exact match**: the proposed first action equals the one action we labelled for "
             "that incident. This is the primary action metric.\n"
             "- **Action: acceptable\\***: the proposed action is on our list of acceptable first actions for "
             "that kind of fault (`ACCEPTABLE_ACTIONS` in `zeroops/schema.py`), e.g. restart *or* scale up "
             "for a memory leak. We wrote that list after the first run had been scored, and every "
             "alternative that changed Jev's score is the action Jev picked; a different SRE team might "
             "draw it differently.\n"
             "- **Severity within 1 level**: severity is on a 4-level scale (SEV4 to SEV1), so only an "
             "error of two or more levels counts as wrong.\n"
             "- **Of those: labelled unsafe**: AUTO on one of the incidents we marked unsafe to automate. "
             "Undefined when a backend never acted.\n"
             "- **Unsafe scenario types automated**: how many of the unsafe templates had at least one "
             "incident automated. Because variants of a template get near-identical answers, the template "
             "is the honest unit; the upper bound is a 95% Wilson interval on that count.\n"
             "- **Unsafe cases paged to a person**: ESCALATE on an unsafe incident.\n"
             "- **Real incidents logged as noise**: OBSERVE on an incident labelled real, i.e. a missed "
             "incident. The unsafe-automation columns do not see these.\n")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--allow-stale", action="store_true",
                    help="include decision files scored against an older corpus version")
    args = ap.parse_args()

    files = sorted(glob.glob(str(RESULTS / DECISIONS_GLOB)))
    if not files:
        console.print("[red]no decisions_*.jsonl found — run scripts/run_eval.py first[/red]")
        return 1

    per_backend: dict[str, list[dict]] = {}
    for f in files:
        name = Path(f).stem.replace("decisions_", "")
        recs = load_records(Path(f))
        versions = {r.get("corpus_version", "") for r in recs}
        if versions != {VERSION} and not args.allow_stale:
            console.print(f"[yellow]skip {name}: corpus version {sorted(versions)} != current {VERSION}; "
                          f"re-run it with scripts/run_eval.py[/yellow]")
            continue
        per_backend[name] = recs
    if not per_backend:
        console.print("[red]no decision files match the current corpus version[/red]")
        return 1

    # empirical price per input token from the OpenRouter run (same model as native Jev)
    rate = None
    if "jev_openrouter" in per_backend:
        toks = sum(r.get("input_tokens", 0) for r in per_backend["jev_openrouter"] if not r.get("error"))
        cost = sum(r.get("cost_usd") or 0 for r in per_backend["jev_openrouter"] if not r.get("error"))
        if toks:
            rate = cost / toks

    metrics: dict[str, dict] = {}
    for name, recs in per_backend.items():
        m = compute_metrics(recs)
        ok = [r for r in recs if not r.get("error")]
        in_tok = [r.get("input_tokens", 0) for r in ok]
        out_tok = [r.get("output_tokens", 0) for r in ok]
        mean_in = statistics.fmean(in_tok) if in_tok else 0
        if name in LOCAL:
            m["cost"]["per_1k_usd"] = 0.0
            m["cost"]["basis"] = "no API fee; GPU and power not costed"
        elif m["cost"]["has_cost"]:
            m["cost"]["basis"] = f"billed usage.cost (mean {mean_in:,.0f} input tokens)"
        elif rate is not None:
            m["cost"]["per_1k_usd"] = round(mean_in * rate * 1000, 4)
            m["cost"]["basis"] = (f"estimated: this API returns no cost, so OpenRouter's billed rate x "
                                  f"{mean_in:,.0f} mean input tokens")
        else:
            m["cost"]["basis"] = "no cost data"
        m["mean_input_tokens"] = round(mean_in, 1)
        m["mean_output_tokens"] = round(statistics.fmean(out_tok), 1) if out_tok else 0
        m["corpus_version"] = VERSION
        metrics[name] = m

    facts = build_facts(per_backend, metrics, VERSION)
    report_md = build_report_md(per_backend, metrics, facts)
    demo = build_demo_payload(per_backend, metrics)

    # write everything only after every piece has been computed
    METRICS.write_text(json.dumps(metrics, indent=2))
    FACTS.write_text(json.dumps(facts, indent=2))
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text(report_md)
    DEMO_DATA.write_text(json.dumps(demo, indent=2))

    table = Table(title=f"ZeroOps results (corpus {VERSION})")
    for c in ["backend", "n", "err", "cat%", "action exact%", "acceptable%", "auto", "unsafe auto",
              "missed real", "p50 ms", "cost/1k $"]:
        table.add_column(c, justify="right" if c != "backend" else "left")
    for name in [n for n in ORDER if n in metrics] + [n for n in metrics if n not in ORDER]:
        m = metrics[name]
        t, a, lat, c = m["decision_quality_pct"], m["autonomy"], m["latency_ms"], m["cost"]
        table.add_row(LABELS.get(name, name), str(m["n"]), str(m["errors"]),
                      fmt(t["failure_category"]), fmt(t["action"]), fmt(t["action_acceptable"]),
                      str(a["auto"]), str(a["unsafe_auto"]), str(a["missed_incidents"]),
                      fmt(lat["p50"]), fmt(c["per_1k_usd"], ".4f", "n/a"))
    console.print(table)
    console.print(f"saved -> {', '.join(rel(p) for p in (METRICS, FACTS, REPORT, DEMO_DATA))}")
    return 0


def build_demo_payload(per_backend: dict[str, list[dict]], metrics: dict[str, dict]) -> dict:
    """Compact per-backend examples for the HyperFrames dashboard and interactive pages."""
    examples = []
    for name in [n for n in ORDER if n in metrics]:
        recs = [r for r in per_backend[name] if not r.get("error")]
        by_arch: dict[str, dict] = {}
        for r in recs:
            by_arch.setdefault(r["archetype"], r)
        picks = []
        for arch in ["bad_deploy", "config_drift", "cpu_saturation", "memory_leak",
                     "dns_failure", "cert_expiry", "security_incident", "data_corruption",
                     "monitoring_fluke", "planned_maintenance"]:
            if arch not in by_arch:
                continue
            r = by_arch[arch]
            p = r["pred"]
            picks.append({
                "id": r["incident_id"], "archetype": r["archetype"], "state": r["state"],
                "gt_action": r["ground_truth"]["correct_action"],
                "gt_safe": r["ground_truth"]["auto_safe"],
                "real_incident": round(p["real_incident"], 3),
                "category": p["failure_category"],
                "category_confidence": round(p["category_confidence"], 3),
                "suspect_component": p["suspect_component"],
                "root_cause": p["root_cause"],
                "deploy_correlated": round(p["deploy_correlated"], 3),
                "severity": round(p["severity"], 2),
                "severity_confidence": round(p["severity_confidence"], 3),
                "blast_radius": round(p["blast_radius"], 2),
                "customer_impact": round(p["customer_impact"], 3),
                "safe_to_autorollback": round(p["safe_to_autorollback"], 3),
                "action": p["proposed_action"],
                "action_conf": round(p["action_confidence"], 3),
                "action_risk": round(p["action_risk"], 2),
                "needs_page": round(p["needs_page"], 3),
                "outcome": r["decision"]["outcome"],
                "rationale": r["decision"]["rationale"],
                "latency_ms": r["latency_ms"],
                "correct_action": r["correct"]["action"],
            })
        examples.append({"backend": name, "label": LABELS.get(name, name), "examples": picks})
    return {"metrics": metrics, "labels": LABELS, "examples": examples,
            "corpus_size": metrics[next(iter(metrics))]["n"], "corpus_version": VERSION}


if __name__ == "__main__":
    raise SystemExit(main())
